name: Terraform deployment

on:
  push:
    branches: ['main']

  workflow_dispatch: #this attribute will enable the manual run to the pipeline


permissions:
  contents: read

# Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
defaults:
  run:
    shell: bash

env:
  TERRAFORM_VERSION: 1.3.0
  TERRAFORM_REGION: ${{ vars.REGION }}

jobs:
  terraform-deploy:
    name: terraform deployment
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.TERRAFORM_REGION }}

      # Install the latest version of Terraform CLI and configure the Terraform
      # CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Init Terraform
        id: init
        run: |
          terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        env:
          TF_VAR_apps: ${{ vars.APPLICATIONS }}
